title: "CareFlow"
remote_theme: pages-themes/cayman@v0.2.0

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2223S2-CS2103T-W09-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
  - jekyll-remote-theme
